{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secretName" . }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
{{ .Values.secret.datatype }}:
{{- if .Values.secret.secretFromValues.enabled}}
{{- if eq .Values.secret.datatype "stringData" }}
  {{- with .Values.secret.secretContents }}
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if eq .Values.secret.datatype "data" }}
  {{- range $key, $value := .Values.secret.secretContents }}
  {{ $key }}: '{{ tpl ($value | b64enc) $ }}'
  {{- end }}
{{- end }}
{{- end }}

{{- if .Values.secret.secretFromFile.enabled }}
{{- if eq .Values.secret.datatype "data" }}
{{- $root := . -}}
{{ range $path, $bytes := .Files.Glob "secrets/*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
{{- end }}
{{- end }}
{{- end }}

{{- end }}

